 name: Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21  # ወደ 21 ተቀይሯል
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace # ስህተት ካለ በዝርዝር እንዲያሳይ

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capyreader-debug-apk
          path: "**/*.apk"
          if-no-files-found: error # ፋይሉ ካልተገኘ እንዲያሳውቀን

